sudo: required
services:
    - docker

before_install:
    - docker build -t ej591541/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true ej591541/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-126205443153"
    bucket_path: "docker-react"
    on:
        branch: develop
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"